adcheck/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^doggy_admin/', include(admin.site.urls)),
    url(r'^accounts/', include('account.urls')),
    url(r'^item/', include('item.urls', namespace="item")),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^$',
        # TemplateView.as_view(template_name="index.html"),
        TemplateView.as_view(template_name="index_ver_4.html"),
        # TemplateView.as_view(template_name="index_pr.html"),
        # TemplateView.as_view(template_name="index_ver_3.html"),
        name='home'
        ),
    url(r'^old/',
        TemplateView.as_view(template_name="index_pr.html"),
        # TemplateView.as_view(template_name="index_ver_4.html")
        ),
    url(r'^file_upload/', include('django_file_form.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    # url(r'^test/$', views.test, name='test'),
    url(r'^items/$', views.ItemList.as_view()),
    url(r'^items/(?P<pk>[0-9]+)$', views.ItemDetail.as_view()),
    url(r'^images/$', views.ImageList.as_view()),
    # url(r'^images/(?P<pk>[0-9]+)$', views.ItemImageList.as_view()),
    url(r'^items/(?P<pk>[0-9]+)/images/$', views.ItemImageList.as_view()),
    url(r'^images/(?P<pk>[0-9]+)$', views.ImageDetail.as_view()),
    url(r'^image_comments/$', views.ImageCommentList.as_view()),
    url(r'^image_comments/(?P<pk>[0-9]+)$',
        views.ImageCommentDetail.as_view()),
    # 아래 Comments/num 은 구버전임
    url(r'^comments/(?P<pk>[0-9]+)$', views.CommentList.as_view()),
    # 아래로 대치하여야 함.
    url(r'^images/(?P<pk>[0-9]+)/comments$', views.CommentList.as_view()),
    url(r'^attach_file/(?P<pk>[0-9]+)$', views.AttachFileDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

item/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<item_id>\d+)$', views.end, name='detail'),
    # url(r'^(?P<item_id>\d+)$', views.detail, name='detail'),
    # url(r'^end/(?P<item_id>\d+)$', views.end, name='end'),
    url(r'^end/add_image/(?P<item_id>\d+)$',
        views.end_addimages, name='end_addimages'),
    url(r'^end/add_files/(?P<item_id>\d+)$',
        views.end_addfiles, name='end_addfiles'),
    url(r'^add_comment$', views.add_comment, name='add_comment'),
    url(r'^(?P<item_id>\d+)/images/$',
        views.end_image_order, name='end_image_order'),
    url(r'^review$', views.review_list, name='review_list'),
    url(r'^review_update/(?P<item_id>\d+)$',
        views.review_update, name='review_update'),
    url(r'^history/$',
        views.history, name='history'),
    url(r'^review_complete/(?P<item_id>\d+)/(?P<status_code>\d+)$',
        views.review_complete, name='review_complete'),
]

item/forms.py
from django import forms
from .models import Item, Image, ImageComment, Review
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
# from django_file_form.forms import FileFormMixin, UploadedFileField
from django_file_form.forms import FileFormMixin, MultipleUploadedFileField


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        # fields = ('title', 'description', 'url', 'status')
        fields = ('title', 'description', 'url',)


class MultiFileInput(forms.FileInput):
    def render(self, name, value, attrs=None):
        attrs['multiple'] = 'multiple'
        return super(MultiFileInput, self).render(name, value, attrs)

    def value_from_datadict(self, data, files, name):
        if hasattr(files, 'getlist'):
            return files.getlist(name)
        else:
            value = files.get(name)
            if isinstance(value, list):
                return value
            else:
                return [value]


class MultiFileField(forms.FileField):
    widget = MultiFileInput
    default_error_messages = {
        'min_num': _(u'Ensure at least %(min_num)s files are uploaded \
            (received %(num_files)s).'),
        'max_num': _(u'Ensure at most %(max_num)s files are uploaded \
            (received %(num_files)s).'),
        'file_size': _(u'File %(uploaded_file_name)s exceeded maximum \
            upload size.'),
    }

    def __init__(self, *args, **kwargs):
        self.min_num = kwargs.pop('min_num', 0)
        self.max_num = kwargs.pop('max_num', None)
        self.maximum_file_size = kwargs.pop('maximum_file_size', None)
        super(MultiFileField, self).__init__(*args, **kwargs)

    def to_python(self, data):
        ret = []
        for item in data:
            ret.append(super(MultiFileField, self).to_python(item))
        return ret

    def validate(self, data):
        super(MultiFileField, self).validate(data)
        num_files = len(data)
        if len(data) and not data[0]:
            num_files = 0
        if num_files < self.min_num:
            raise ValidationError(
                self.error_messages['min_num'] %
                {'min_num': self.min_num, 'num_files': num_files}
            )
        if num_files > self.max_num:
            raise ValidationError(
                self.error_messages['max_num'] %
                {'max_num': self.max_num, 'num_files': num_files}
            )
        if num_files > 0:
            for uploaded_file in data:
                if uploaded_file.size > self.maximum_file_size:
                    raise ValidationError(
                        self.error_messages['file_size'] %
                        {'upload_file_name': uploaded_file.name}
                    )


class ImageForm(forms.Form):
    files = MultiFileField(
        max_num=20, min_num=0, maximum_file_size=1024*1024*5
    )


class ImageCommentForm(forms.ModelForm):
    class Meta:
        model = ImageComment
        fields = ('text',)


class ReviewForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea,
        label='심의총평',
        required=False
    )
    disqulification = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=Review.DISQUALIFICATION_CHOICES,
        label='이슈 분류코드',
        required=False
    )


class NewImageForm(FileFormMixin, forms.Form):
    # input_file = UploadedFileField()
    input_file = MultipleUploadedFileField()


class AttachFileForm(FileFormMixin, forms.Form):
    input_file = MultipleUploadedFileField()

item/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import Item, Image, ImageComment, Review, AttachFile
from .forms import ItemForm, ImageForm, ImageCommentForm, ReviewForm
from .forms import NewImageForm, AttachFileForm
# for AJAX view
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.core.urlresolvers import reverse


@login_required
def new(request):
    if request.method == 'POST':
        item_form = ItemForm(request.POST)
        new_image_form = NewImageForm(request.POST)
        if item_form.is_valid():
            new_item = item_form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            if new_image_form.is_valid():
                new_file_list = new_image_form.cleaned_data['input_file']
                print(new_file_list)
                new_order = 1
                for afile in new_file_list:
                    image = Image.objects.create(
                                item=new_item, order=new_order, image=afile
                            )
                    new_order += 1
                new_image_form.delete_temporary_files()
            else:
                print('image form is not valid!!')

            return redirect(reverse(
                                'item:detail',
                                kwargs={'item_id': new_item.id})
                            )
        else:
            return render(request, 'item/new.html',
                          {'item_form': item_form,
                           'new_image_form': new_image_form}
                          )

    else:
        item_form = ItemForm()
        new_image_form = NewImageForm()

        return render(request,
                      'item/new.html', {
                           'item_form': item_form,
                           'new_image_form': new_image_form}
                      )


@login_required
def detail(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    qs = Review.objects.filter(item_id=item_id)
    if qs.exists():
        data = {'text': item.review.text,
                'disqulification': item.review.disqulification}
        review_form = ReviewForm(initial=data)
    else:
        review_form = ReviewForm()
    context = {
        'item': item,
        'review_form': review_form,
        # 'is_new': is_new
    }
    return render(request, 'item/detail.html', context)


@login_required
def end(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    qs = Review.objects.filter(item_id=item_id)
    if qs.exists():
        data = {'text': item.review.text,
                'disqulification': item.review.disqulification}
        review_form = ReviewForm(initial=data)
    else:
        review_form = ReviewForm()
    new_image_form = NewImageForm()
    context = {
        'item': item,
        'review_form': review_form,
        'new_image_form': new_image_form
        # 'is_new': is_new
    }
    return render(request, 'item/end.html', context)


@login_required
def end_addimages(request, item_id):
    if request.method == 'POST':
        new_image_form = NewImageForm(request.POST)
        if new_image_form.is_valid():
            new_file_list = new_image_form.cleaned_data['input_file']
            item = get_object_or_404(Item, pk=item_id)
            images = item.images.all()
            order = 1
            for aimage in images:
                aimage.order = order
                aimage.save()
                order += 1
            for afile in new_file_list:
                image = Image.objects.create(
                            item=item, order=order, image=afile)
                order += 1
            new_image_form.delete_temporary_files()
    return redirect(reverse('item:detail', kwargs={'item_id': item_id}))


@login_required
def end_addfiles(request, item_id):
    if request.method == 'POST':
        attach_file_form = AttachFileForm(request.POST)
        if attach_file_form.is_valid():
            attach_file_list = attach_file_form.cleaned_data['input_file']
            item = get_object_or_404(Item, pk=item_id)
            for afile in attach_file_list:
                afile = AttachFile.objects.create(
                            item=item, file=afile)
            attach_file_form.delete_temporary_files()
    return redirect(reverse('item:detail', kwargs={'item_id': item_id}))


@login_required
@require_POST
def add_comment(request):
    image_id = request.POST.get('id')
    text = request.POST.get('text')
    if image_id and text:
        # print('포스트 정보를 정상적으로 받았습니다.')
        # print(image_id)
        # print(text)
        # print(request.user)
        image_comment_form = ImageCommentForm(request.POST)
        image_comment_form.text = text
        # print(image_comment_form.text)
        if image_comment_form.is_valid():
            cd = image_comment_form.cleaned_data
            image_comment_form.text = cd['text']
            # print('image_comment_form.is_valid():')
            # print('POSTed text is', image_comment_form.text)
            # print('Yes real vailidated!!')
            new_image_comment = image_comment_form.save(commit=False)
            new_image_comment.image = Image.objects.get(pk=image_id)
            new_image_comment.user = request.user
            image_comment_form.save()
            # print(new_image_comment)
            return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'ko'})


@login_required
def review_list(request, user=None, status=None):
    qs = request.GET
    if 'status' in qs:
        status = qs['status']
    if 'user' in qs:
        user = qs['user']
    if status == 'None' and user == 'None':
        item_list = Item.objects.all()
    elif status == 'None' and user:
        item_list = Item.objects.filter(user__username=user)
    elif status and user == 'None':
        item_list = Item.objects.filter(status=status)
    elif status and user:
        item_list = Item.objects.filter(status=status, user__username=user)
    else:
        item_list = Item.objects.all()
    if request.user.profile.user_level == 'reviewer':
        item_list = item_list.exclude(status='0').exclude(status='6')\
            .exclude(status='7').exclude(status='8')
    context = {
        'item_list': item_list,
        'status': status,
        'user': user
    }
    return render(request, 'item/review_list.html', context)


@login_required
def review_update(request, item_id):
    if request.method == 'POST':
        level = request.user.profile.user_level
        print(level)
        if level == 'staff' or level == 'reviewer':
            print('권한 확인됨')
            review = ReviewForm(request.POST)
            if review.is_valid():
                print('폼은 유효합니다.')
                cd = review.cleaned_data
                qs = Review.objects.filter(item_id=item_id)
                # 리뷰 저장하기
                if qs.exists():
                    print('업데이트로 진행합니다.')
                    # 업데이트 하기
                    qs.update(
                        text=cd['text'],
                        user=request.user,
                        disqulification=cd['disqulification']
                    )
                    print('업데이트 되었습니다!!!!!')
                else:
                    Review.objects.create(
                        text=cd['text'],
                        disqulification=cd['disqulification'],
                        user=request.user,
                        item=Item.objects.get(pk=item_id)
                    )
                    print('리뷰를 신규 생성하였습니다 :))')
                # 광고 아이템 상태값 변경하기
                aitem = Item.objects.get(pk=item_id)
                print('아이템 상태: ', aitem.status)
                if aitem.status == '1' or aitem.status == '2':
                    aitem.status = '3'
                    aitem.save()
            else:
                print('폼이 유효하지 않습니다.')
            user = request.user
            print(user)
            context = {
                'review': Review.objects.get(item_id=item_id),
                'item_id': item_id,
                'aitem': aitem
            }
            return render(request,
                          'item/review_update_confirm.html',
                          context)

        else:  # 유저레벨이 관리자나 리뷰어가 아닌경우
            return redirect('dashboard')
    else:  # POST이외의 방식으로 접근하는 경우
        return redirect('dashboard')


@login_required
def history(request):
    level = request.user.profile.user_level
    print(level)
    if level == 'staff' or level == 'reviewer':
        # comment_list = ImageComment.objects.filter(user=request.user)
        comment_list = Item.objects.filter(
                            images__comments__user=request.user).distinct()
        review_list = Item.objects.filter(
                            review__user=request.user).distinct()

        context = {
            'comment_list': comment_list,
            'review_list': review_list
        }
        return render(request,
                      'item/history.html',
                      context)
    else:
        return redirect('dashboard')


@login_required
def review_complete(request, item_id, status_code):
    if request.method == 'GET':
        level = request.user.profile.user_level
        print(level)
        if level == 'staff':
            print('권한 확인됨')
            qs = Item.objects.filter(pk=item_id)
            if qs.exists():
                print('광고가 존재합니다.')
                if status_code in ['5', '6', '7', '8']:
                    qs.update(
                        status=status_code
                    )
                    print('업데이트 되었습니다!!!!!')
                    aitem = Item.objects.get(pk=item_id)
                    context = {
                        'review': Review.objects.get(item_id=item_id),
                        'item_id': item_id,

item/templates/item/end.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}ADcheck > 상세: {{ item.title }}{% endblock title %}

{% block react_js %}
  {# <script src="https://fb.me/react-15.0.0-rc.1.min.js"></script> #}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/redux/3.3.1/redux.js"></script>
  <script src="https://npmcdn.com/react-redux@4.4.1/dist/react-redux.js"></script>
  {# <script src="https://cdnjs.cloudflare.com/ajax/libs/redux/3.3.1/redux.min.js"></script> #}

{% endblock react_js %}

{% block custom_css %}
<link rel="stylesheet" href="{% static "ajaxuploader/css/fileuploader.css" %}">    
{% endblock custom_css %}


{% block content %}
<div class="row">
  <div class="small-12 columns">
    <h4>심의정보</h4>
    <table>
      <tr>
        <th width="100px">광고 제목</th> <td>{{ item.title }}</td>
      </tr>
      <tr>
        <th>심의 상태</th> <td><span class="{{ item.status_name.3 }} label">{{ item.status_name.0 }}</span> {{ item.status_name.4 }}</td>
      </tr>
      {% if request.user.profile.user_level == 'client' and item.review %}
      <tr>
        <th>심의 문구</th> <td>{{ item.review.text|linebreaksbr }}</td>
      </tr> <tr>
        <th>위반 사항</th> <td>{{ item.review.disqulification_text|linebreaksbr }}</td>
      </tr>
      {% endif %}
      <tr>
        <th>등록일</th> <td>{{ item.created }}</td>
      </tr> <tr>
        <th>수정일</th> <td>{{ item.modified }}</td>
      </tr> <tr>
        <th>제품링크</th> <td><a href="{{ item.url }}" target="_blank">{{ item.url }}</a></td>
      </tr> <tr>
        <th>제품 설명</th> <td>{{ item.description|linebreaksbr }}</td>
      </tr>
    </table>
  </div>
</div>

<div id="end-container" data-itemId="{{ item.id }}"
{% if request.user.profile.user_level != 'client' %} data-isReadOnly="false"{% endif %}
{% if request.user == item.user %} data-isOwner="true"{% endif %}
></div>


{# 작성자: {{ item.user }} <br /> 로그인: {{ request.user }} #}
{% if request.user == item.user %}
<div class="row">
  <div class="small-12 columns callout panel">
    <h3>광고 이미지 추가하기</h3>
    <form
      id="upload-images"
      action="{% url 'item:end_addimages' item.id %}"
      method="post"
      enctype="multipart/form-data"
    >
      <div class="row">
        <div class="small-12 large-12 columns panel">
          <h4>Step 1. 추가할 이미지들을 선택해 주세요.</h4>
            {{ new_image_form }}
            {% csrf_token %}
            {% include 'item/upload_template.html' %}
        </div>
        <div class="small-12 large-12 columns panel">
          <h4>Step 2. 이미지 추가하기 버튼을 눌러주세요.</h4>
          <input class="button" type="submit" value="이미지 추가하기">
        </div>
      </div>
      {# <p>파일의 추가 선택 / 삭제가 가능합니다.</p> #}
      {# <div class="small-12 columns"> #}
      {# <p><input class="button" type="submit" value="이미지 추가하기"></p> #}
      {# </div> #}
    </form>
  </div>
  <div class="small-12 columns callout panel">
    <h3>증빙자료 첨부하기</h3>
    <form
      id="upload-files"
      action="{% url 'item:end_addfiles' item.id %}"
      method="post"
      endtype="multipart/form-data"
    >
      <div class="row">
        <div class="small-12 large-12 columns panel">
          <h4>1. 첨부할 파일들을 선택해 주세요.</h4>
          <dl>
            <dt>광고심의필증:</dt>
            <dd>건강기능식품, 특수용도식품의 경우 사전광고심의필증 및 심의 광고물을 함께 첨부해주세요.</dd>
            <dt>기타 구비서류:</dt>
            <dd>화장품 기능성 심사보고서, 의약외품 품목허가서, 인증 관련 증빙자료 등</dd>
          </dl>
          {{ new_image_form }}
          {% csrf_token %}
          {% include 'item/upload_template.html' %}
        </div>
        <div class="small-12 large-12 columns panel">
          <h4>2. 자료 추가하기 버튼을 눌러주세요.</h4>
          <p><input class="button" type="submit" value="자료 추가하기"></p>
          <dl>
            <dt>첨부된 파일들</dt>
            {% for file in item.attached_files.all %}
            <dd><a href="{{file}}"> {{ file.filename }}</a>
            {# <a class="label alert" href="#">첨부화일 삭제</a></dd>  #}
            {% empty %}
              <span>첨부된 파일이 없습니다.</span>
            {% endfor %}
          </dl>
        </div>
      </div>
    </form>
  </div>
  <div class="small-12 columns callout panel">
    <a
      href="{% url 'item:end_image_order' item.id %}"
      class="button warning"
    >이미지 순서 변경하기</a>
  </div>
</div>

{% else %}
  {# <p>당신은 이 글의 작성자가 아닙니다.</p> #}
{% endif %}


{# 리뷰어/관리자의 경우 심의 평가하기 내용이 노출되는 영역 #}
{% with level=request.user.profile.user_level %}
  {% if level == 'staff' or level == 'reviewer' %}
  <div class="row">
    <div class="small-12 columns panel callout">
      <form action="{% url 'item:review_update' item.id %}" method="post">
        {# {{ is_new }} #}
        {# <form action="#" method="post"> #}
        {{review_form.as_p}}
        {% csrf_token %}
        <input class="large success round button" type="submit" value="심의완료하기">
      </form>
    </div>
  </div>
  {% endif %}
{% endwith %}

{% endblock content %}

{% block custom_js %}
<script type="text/babel" src="{% static 'js/end.js' %}"></script>
<script src="{% static "ajaxuploader/js/fileuploader.js" %}"></script>
<script src="{% static "file_form/file_form.js" %}"></script>
<script>
$(function() {
    initUploadFields(
      $('#upload-images'),
      {
        validation: {
          acceptFiles: 'image/*',
          sizeLimit: 10000000
        }
      }
    );
    initUploadFields(
      $('#upload-files'),
      {
        validation: {
          sizeLimit: 10000000
        }
      }
    );
});
</script>

{% endblock custom_js %}

item/templates/item/end_image_order.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}ADcheck > 이미지 순서 변경 페이지{% endblock title %}

{% block react_js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.0.0/react.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.0.0/react-dom.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/redux/3.3.1/redux.js"></script>
  <script src="https://npmcdn.com/react-redux@4.4.1/dist/react-redux.js"></script>
  <script src="https://npmcdn.com/redux-thunk@2.0.1/dist/redux-thunk.min.js"></script>
{% endblock react_js %}

{% block custom_css %}{% endblock custom_css %}

{% block content %}
<div class="row">
  <div class="small-12 columns">
    <div id="image-list"></div>
    <div id="end-container" data-itemId="{{ item_id }}"></div>
    <a href="{% url 'item:detail' item_id %}" class="button">뒤로 이동</a>
  </div>
</div>
{% endblock content %}

{% block custom_js %}
<script>
$(function() {

});
</script>
<script type="text/babel" src="{% static 'js/end_image_order.js' %}"></script>
{% endblock custom_js %}

item/templates/item/review_list.html
{% extends "base.html" %}

{% block title %}[{{ request.user.profile.user_level }}] 심의 리스트{% endblock title %}

{% block content %}
{% if request.user.profile.user_level == 'staff' or request.user.profile.user_level == 'reviewer' %}
<div class="row">
    <div class="small-12">
        <h2>광고 목록</h2>
        {% if status != None and status != 'None' %}
            상황 필터: {{ status }}
            <a href="{% url "item:review_list" %}?status=None&user={{ user }}"> 필터 초기화 </a>
        {% endif %}
        {% if user != None and user != 'None' %}
            사용자 필터: {{ user }}
             <a href="{% url 'item:review_list' %}?status={{ status }}&user=None"> 필터 초기화 </a>
        {% endif %}
        {% if status or user %}
            <a href="{% url 'item:review_list' %}">모든 필터 초기화</a>
            
        {% endif %}

        <table>
            <thead>
                <th>id</th>
                <th>진행 상황</th>
                <th>광고주명 </a> </th>
                <th>광고 제목</th>
                <th>등록일시</th>
                <th>업데이트</th>
            </thead>
            {% for aitem in item_list %}
            {# {% for aitem in item_list|dictsort:"created" %} #}
            {# {% for aitem in item_list|dictsort:"status" %} #}
            <tr>
                <td>{{ aitem.id }}</td>
                <td>
                    <a href="{% url 'item:review_list' %}?status={{ aitem.status }}&user={{ user }}">
                        <span class="{{ aitem.status_name.3 }} label">{{ aitem.status_name.0 }}</span> </a> </td>
                <td>
                    <a href="{% url 'item:review_list' %}?status={{ status }}&user={{ aitem.user }}">
                        {{ aitem.user.first_name }} </a> </td>
                <td> <a href="{% url 'item:detail' aitem.id %}">{{ aitem }}</a> </td>
                <td> {{ aitem.created|date:"Y-m-d H:m" }} </td>
                <td> {{ aitem.modified|timesince }} 전 </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% else %}
<div class="row"><div class="small-12 columns"><h1>접근 권한이 없습니다.</h1>
<a href="{% url 'dashboard' %}">대시보드로 이동하기</a>
</div></div>

{% endif %}
    
{% endblock content %}

item/templates/item/review_update_confirm.html
{% extends "base.html" %}

{% block title %}
    {{ request.user.profile.user_level }}
    | 리뷰 업데이트 확인 페이지
{% endblock title %}

{% block content %}
<div class="row">
    <div class="small-12">
    <h1>아래와 같이 업데이트 되었습니다.</h1>
        <p>광고 진행상황: <span class="{{ aitem.status_name.3 }} label">{{ aitem.status_name.0 }}</span></p>
        <p>심의 총평: {{ review.text }}</p>
        <p>이슈 분류 코드: {{ review.disqulification }}</p>
    </div>

    <div class="small-12 columns panel">
    {% if request.user.profile.user_level == 'reviewer' %}
        <a href="{% url 'item:detail' item_id %}" class="button">광고 상세페이지로 돌아가기</a>
    {% endif %}
        <a href="{% url 'item:review_list' %}" class="button">리스트로 이동하기</a>
    </div>

    {% if request.user.profile.user_level == 'staff' %}
    <div class="small-6 columns panel callout">
        <h2>심의 승인 하기</h2>
        <ul>
            <li>
                <a href="{% url 'item:review_complete' item_id=item_id status_code=6 %}" class="success button">6. 심의완료됨-승인</a>
            </li>
            <li>
                <a href="{% url 'item:review_complete' item_id=item_id status_code=7 %}" class="warning button">7.심의완료됨-조건부승인</a>
            </li>
            <li>
                <a href="{% url 'item:review_complete' item_id=item_id status_code=8 %}" class="alert button">8.심의완료됨-광고불가</a>
            </li>
        </ul>
    </div>
    <div class="small-6 columns panel callout">
        <ul>
            <h2>심의 반려 하기</h2>
            <p>(리뷰어의 심의 내용에 이상이 있어서 리뷰어의 재심의를 요청하는 것)</p>
            <li>
                <a href="{% url 'item:review_complete' item_id=item_id status_code=5 %}" class="alert button">'5.심의확인-반려됨' 으로 변경하기</a>
            </li>
        </ul>
        {% endif %}
    </div>
</div>


    
{% endblock content %}